version: '3.1'
services:
  dbmysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
    ports:
      - 8350:3306
    environment:
      MYSQL_ROOT_PASSWORD: ETxGkUcEZM7M22tP5
      MYSQL_DATABASE: api-template
  redis:
    image: redis
    container_name: cache
    ports:
      - 8353:6379
  restapi:
    image: api
    build:
      context: ./
    restart: always
    ports:
      - 8351:8351
    environment:
      # General setting
      - PORT=8351
      - JWT_SECRET="secretKey"
      # Mysql setting
      - DB_PASSWORD=ETxGkUcEZM7M22tP5
      - DB_NAME=api-template
      - DB_PORT=3306
      - DB_USER=root
      - DB_HOST=mysql
      - NODE_ENV=development
      # Redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - dbmysql
      - redis
    links:
      - dbmysql:mysql
      - redis:redis
volumes:
  db_data: { }
